# Generated by Django 5.2.1 on 2025-05-26 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrrecord',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ocrrecord',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
