# Generated by Django 5.2.1 on 2025-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_rename_uploaded_at_ocrrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrecord',
            name='template_choice',
            field=models.CharField(default='modern_minimal', max_length=100),
        ),
    ]
